version: '3.9'

services:
  app:
    build: .
    container_name: shorter-url
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm run start:dev"

  db:
    image: postgres
    container_name: shorter-url-db
    restart: always
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: dev123 # only in dev
      POSTGRES_DB: shorturldb # only in dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
